#!/usr/bin/env python3
"""Regenerate the Remixicon subset served from public/remixicon/.

The full package is 110 KB of CSS defining 2271 icons plus a 125 KB woff2. This
site uses ~45 of them, so both are subset down to roughly 2 KB + 4 KB.

Run this after adding or removing any `ri-*` class in src/, otherwise a newly
referenced icon has no glyph and renders as a blank box:

    python3 scripts/build-remixicon-subset.py

Requires fontTools (`pip3 install fonttools brotli`) and the remixicon package
in node_modules. Both outputs are committed, so this only needs running when the
set of icons changes.
"""
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
PKG = ROOT / "node_modules" / "remixicon" / "fonts"
OUT = ROOT / "public" / "remixicon"


def main() -> int:
    css_path = PKG / "remixicon.css"
    if not css_path.exists():
        print(f"error: {css_path} not found — is remixicon installed?", file=sys.stderr)
        return 1

    css = css_path.read_text()

    used = set()
    for path in SRC.rglob("*"):
        if path.suffix in {".js", ".jsx", ".css"} and path.is_file():
            text = path.read_text(encoding="utf-8", errors="ignore")
            used.update(re.findall(r"\bri-[a-z0-9-]+\b", text))

    mapping = dict(
        re.findall(r'\.(ri-[a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"', css)
    )
    resolved = {name: mapping[name] for name in sorted(used) if name in mapping}
    missing = sorted(name for name in used if name not in mapping)

    print(f"referenced={len(used)}  resolved={len(resolved)}  unknown={len(missing)}")
    if missing:
        # Not fatal: these render as blank boxes and should be corrected in src.
        print("  WARNING — not real Remixicon classes:", ", ".join(missing))

    OUT.mkdir(parents=True, exist_ok=True)
    unicodes = ",".join("U+" + cp.upper() for cp in resolved.values())

    subprocess.run(
        [
            sys.executable, "-m", "fontTools.subset",
            str(PKG / "remixicon.woff2"),
            f"--unicodes={unicodes}",
            "--flavor=woff2",
            f"--output-file={OUT / 'remixicon.subset.woff2'}",
        ],
        check=True,
    )

    rules = "\n".join(f'.{n}:before{{content:"\\{cp}"}}' for n, cp in resolved.items())
    (OUT / "remixicon.subset.css").write_text(
        f"""/* Remixicon subset — {len(resolved)} icons actually used by this site.
 * GENERATED by scripts/build-remixicon-subset.py — do not edit by hand.
 * Re-run that script after adding a new ri-* class. */
@font-face{{font-family:remixicon;src:url("/remixicon/remixicon.subset.woff2") format("woff2");font-display:swap;font-weight:400;font-style:normal}}
[class^="ri-"],[class*=" ri-"]{{font-family:remixicon!important;font-style:normal;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}}
{rules}
"""
    )

    for f in ("remixicon.subset.css", "remixicon.subset.woff2"):
        print(f"  {f}: {os.path.getsize(OUT / f)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
