#!/usr/bin/env node
/**
 * Post-build step: generate sitemap.xml from the pages that were actually built.
 *
 * The sitemap used to be hand-maintained. That meant it still listed 54 URLs on
 * the previous host, with lastmod dates frozen at
 * whenever someone last remembered to edit them, and no relationship to the
 * pages that exist. Generating it from build/p (what prerender.js just wrote)
 * means it cannot drift: a page that exists is listed, a page that does not is
 * not, and lastmod is the date of the build that produced it.
 *
 * Runs after prerender.js.
 */
const fs = require("fs");
const path = require("path");

const BUILD_DIR = process.env.BUILD_PATH
  ? path.resolve(process.env.BUILD_PATH)
  : path.resolve(__dirname, "..", "build");

const SITE = "https://routefacilecarrental.com";
const LANGS = ["en", "fr", "ar"];
const XDEFAULT = "en";

// Pages that change as stock and pricing change, versus copy that rarely moves.
const FREQUENT = new Set(["", "ourfleetlist", "offerspage", "location", "blogs"]);
const priorityFor = (p) => (p === "" ? "1.0" : FREQUENT.has(p) ? "0.9" : "0.7");
const changefreqFor = (p) => (FREQUENT.has(p) ? "daily" : "monthly");

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/"/g, "&quot;");

function main() {
  const prerenderDir = path.join(BUILD_DIR, "p");
  if (!fs.existsSync(prerenderDir)) {
    console.log("[sitemap] no prerendered pages — skipping");
    return;
  }

  // Take the English set as the canonical list of paths; every page is written
  // for all three languages, so one language defines the shape.
  const enDir = path.join(prerenderDir, XDEFAULT);
  if (!fs.existsSync(enDir)) {
    console.log("[sitemap] no English pages — skipping");
    return;
  }

  const paths = fs
    .readdirSync(enDir)
    .filter((f) => f.endsWith(".html"))
    .map((f) => (f === "index.html" ? "" : f.replace(/\.html$/, "")))
    .sort();

  const lastmod = new Date(
    fs.statSync(path.join(enDir, "index.html")).mtime
  ).toISOString().slice(0, 10);

  const urls = [];
  for (const p of paths) {
    for (const lng of LANGS) {
      const loc = `${SITE}/${lng}${p ? `/${p}` : ""}`;
      const alts = LANGS.map(
        (l) =>
          `    <xhtml:link rel="alternate" hreflang="${l}" href="${esc(
            `${SITE}/${l}${p ? `/${p}` : ""}`
          )}" />`
      ).join("\n");
      urls.push(
        `  <url>\n` +
          `    <loc>${esc(loc)}</loc>\n` +
          `    <lastmod>${lastmod}</lastmod>\n` +
          `    <changefreq>${changefreqFor(p)}</changefreq>\n` +
          `    <priority>${priorityFor(p)}</priority>\n` +
          `${alts}\n` +
          `    <xhtml:link rel="alternate" hreflang="x-default" href="${esc(
            `${SITE}/${XDEFAULT}${p ? `/${p}` : ""}`
          )}" />\n` +
          `  </url>`
      );
    }
  }

  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!-- Generated by scripts/sitemap.js from the pages in build/p. Do not edit\n` +
    `     by hand: the next build overwrites it. -->\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n` +
    `        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n\n` +
    urls.join("\n\n") +
    `\n\n</urlset>\n`;

  fs.writeFileSync(path.join(BUILD_DIR, "sitemap.xml"), xml);
  console.log(
    `[sitemap] wrote ${urls.length} URLs (${paths.length} pages × ${LANGS.length} languages), lastmod ${lastmod}`
  );
}

try {
  main();
} catch (err) {
  console.error("[sitemap] skipped:", err.message);
}
