#!/usr/bin/env python3
"""Generate INSERT statements to seed the `countries` table.

Row #1 is United Arab Emirates (existing users in this DB have country_id=1).
The remaining rows are alphabetical ISO 3166-1 countries. The id range covers
all values currently referenced by users.country_id (max observed = 246).
"""
import sys

# (code, name_en, name_ae, phone_code)
# Arabic names: best-effort common translations; pure ASCII fallback to English.
COUNTRIES = [
    ("AE", "United Arab Emirates", "الإمارات العربية المتحدة", "971"),
    ("AF", "Afghanistan", "أفغانستان", "93"),
    ("AL", "Albania", "ألبانيا", "355"),
    ("DZ", "Algeria", "الجزائر", "213"),
    ("AS", "American Samoa", "ساموا الأمريكية", "1684"),
    ("AD", "Andorra", "أندورا", "376"),
    ("AO", "Angola", "أنغولا", "244"),
    ("AI", "Anguilla", "أنغويلا", "1264"),
    ("AQ", "Antarctica", "القارة القطبية الجنوبية", "672"),
    ("AG", "Antigua and Barbuda", "أنتيغوا وباربودا", "1268"),
    ("AR", "Argentina", "الأرجنتين", "54"),
    ("AM", "Armenia", "أرمينيا", "374"),
    ("AW", "Aruba", "أروبا", "297"),
    ("AU", "Australia", "أستراليا", "61"),
    ("AT", "Austria", "النمسا", "43"),
    ("AZ", "Azerbaijan", "أذربيجان", "994"),
    ("BS", "Bahamas", "الباهاما", "1242"),
    ("BH", "Bahrain", "البحرين", "973"),
    ("BD", "Bangladesh", "بنغلاديش", "880"),
    ("BB", "Barbados", "بربادوس", "1246"),
    ("BY", "Belarus", "بيلاروسيا", "375"),
    ("BE", "Belgium", "بلجيكا", "32"),
    ("BZ", "Belize", "بليز", "501"),
    ("BJ", "Benin", "بنين", "229"),
    ("BM", "Bermuda", "برمودا", "1441"),
    ("BT", "Bhutan", "بوتان", "975"),
    ("BO", "Bolivia", "بوليفيا", "591"),
    ("BA", "Bosnia and Herzegovina", "البوسنة والهرسك", "387"),
    ("BW", "Botswana", "بوتسوانا", "267"),
    ("BR", "Brazil", "البرازيل", "55"),
    ("IO", "British Indian Ocean Territory", "إقليم المحيط الهندي البريطاني", "246"),
    ("VG", "British Virgin Islands", "جزر العذراء البريطانية", "1284"),
    ("BN", "Brunei", "بروناي", "673"),
    ("BG", "Bulgaria", "بلغاريا", "359"),
    ("BF", "Burkina Faso", "بوركينا فاسو", "226"),
    ("BI", "Burundi", "بوروندي", "257"),
    ("KH", "Cambodia", "كمبوديا", "855"),
    ("CM", "Cameroon", "الكاميرون", "237"),
    ("CA", "Canada", "كندا", "1"),
    ("CV", "Cape Verde", "الرأس الأخضر", "238"),
    ("KY", "Cayman Islands", "جزر كايمان", "1345"),
    ("CF", "Central African Republic", "جمهورية أفريقيا الوسطى", "236"),
    ("TD", "Chad", "تشاد", "235"),
    ("CL", "Chile", "تشيلي", "56"),
    ("CN", "China", "الصين", "86"),
    ("CX", "Christmas Island", "جزيرة عيد الميلاد", "61"),
    ("CC", "Cocos Islands", "جزر كوكوس", "61"),
    ("CO", "Colombia", "كولومبيا", "57"),
    ("KM", "Comoros", "جزر القمر", "269"),
    ("CK", "Cook Islands", "جزر كوك", "682"),
    ("CR", "Costa Rica", "كوستاريكا", "506"),
    ("HR", "Croatia", "كرواتيا", "385"),
    ("CU", "Cuba", "كوبا", "53"),
    ("CW", "Curacao", "كوراساو", "599"),
    ("CY", "Cyprus", "قبرص", "357"),
    ("CZ", "Czech Republic", "جمهورية التشيك", "420"),
    ("CD", "Democratic Republic of the Congo", "جمهورية الكونغو الديمقراطية", "243"),
    ("DK", "Denmark", "الدنمارك", "45"),
    ("DJ", "Djibouti", "جيبوتي", "253"),
    ("DM", "Dominica", "دومينيكا", "1767"),
    ("DO", "Dominican Republic", "جمهورية الدومينيكان", "1809"),
    ("TL", "East Timor", "تيمور الشرقية", "670"),
    ("EC", "Ecuador", "الإكوادور", "593"),
    ("EG", "Egypt", "مصر", "20"),
    ("SV", "El Salvador", "السلفادور", "503"),
    ("GQ", "Equatorial Guinea", "غينيا الاستوائية", "240"),
    ("ER", "Eritrea", "إريتريا", "291"),
    ("EE", "Estonia", "إستونيا", "372"),
    ("ET", "Ethiopia", "إثيوبيا", "251"),
    ("FK", "Falkland Islands", "جزر فوكلاند", "500"),
    ("FO", "Faroe Islands", "جزر فارو", "298"),
    ("FJ", "Fiji", "فيجي", "679"),
    ("FI", "Finland", "فنلندا", "358"),
    ("FR", "France", "فرنسا", "33"),
    ("PF", "French Polynesia", "بولينزيا الفرنسية", "689"),
    ("GA", "Gabon", "الغابون", "241"),
    ("GM", "Gambia", "غامبيا", "220"),
    ("GE", "Georgia", "جورجيا", "995"),
    ("DE", "Germany", "ألمانيا", "49"),
    ("GH", "Ghana", "غانا", "233"),
    ("GI", "Gibraltar", "جبل طارق", "350"),
    ("GR", "Greece", "اليونان", "30"),
    ("GL", "Greenland", "جرينلاند", "299"),
    ("GD", "Grenada", "غرينادا", "1473"),
    ("GU", "Guam", "غوام", "1671"),
    ("GT", "Guatemala", "غواتيمالا", "502"),
    ("GG", "Guernsey", "غيرنزي", "44"),
    ("GN", "Guinea", "غينيا", "224"),
    ("GW", "Guinea-Bissau", "غينيا بيساو", "245"),
    ("GY", "Guyana", "غيانا", "592"),
    ("HT", "Haiti", "هايتي", "509"),
    ("HN", "Honduras", "هندوراس", "504"),
    ("HK", "Hong Kong", "هونغ كونغ", "852"),
    ("HU", "Hungary", "المجر", "36"),
    ("IS", "Iceland", "آيسلندا", "354"),
    ("IN", "India", "الهند", "91"),
    ("ID", "Indonesia", "إندونيسيا", "62"),
    ("IR", "Iran", "إيران", "98"),
    ("IQ", "Iraq", "العراق", "964"),
    ("IE", "Ireland", "أيرلندا", "353"),
    ("IM", "Isle of Man", "جزيرة مان", "44"),
    ("IL", "Israel", "إسرائيل", "972"),
    ("IT", "Italy", "إيطاليا", "39"),
    ("CI", "Ivory Coast", "ساحل العاج", "225"),
    ("JM", "Jamaica", "جامايكا", "1876"),
    ("JP", "Japan", "اليابان", "81"),
    ("JE", "Jersey", "جيرزي", "44"),
    ("JO", "Jordan", "الأردن", "962"),
    ("KZ", "Kazakhstan", "كازاخستان", "7"),
    ("KE", "Kenya", "كينيا", "254"),
    ("KI", "Kiribati", "كيريباتي", "686"),
    ("XK", "Kosovo", "كوسوفو", "383"),
    ("KW", "Kuwait", "الكويت", "965"),
    ("KG", "Kyrgyzstan", "قيرغيزستان", "996"),
    ("LA", "Laos", "لاوس", "856"),
    ("LV", "Latvia", "لاتفيا", "371"),
    ("LB", "Lebanon", "لبنان", "961"),
    ("LS", "Lesotho", "ليسوتو", "266"),
    ("LR", "Liberia", "ليبيريا", "231"),
    ("LY", "Libya", "ليبيا", "218"),
    ("LI", "Liechtenstein", "ليختنشتاين", "423"),
    ("LT", "Lithuania", "ليتوانيا", "370"),
    ("LU", "Luxembourg", "لوكسمبورغ", "352"),
    ("MO", "Macau", "ماكاو", "853"),
    ("MK", "Macedonia", "مقدونيا", "389"),
    ("MG", "Madagascar", "مدغشقر", "261"),
    ("MW", "Malawi", "مالاوي", "265"),
    ("MY", "Malaysia", "ماليزيا", "60"),
    ("MV", "Maldives", "جزر المالديف", "960"),
    ("ML", "Mali", "مالي", "223"),
    ("MT", "Malta", "مالطا", "356"),
    ("MH", "Marshall Islands", "جزر مارشال", "692"),
    ("MR", "Mauritania", "موريتانيا", "222"),
    ("MU", "Mauritius", "موريشيوس", "230"),
    ("YT", "Mayotte", "مايوت", "262"),
    ("MX", "Mexico", "المكسيك", "52"),
    ("FM", "Micronesia", "ميكرونيزيا", "691"),
    ("MD", "Moldova", "مولدوفا", "373"),
    ("MC", "Monaco", "موناكو", "377"),
    ("MN", "Mongolia", "منغوليا", "976"),
    ("ME", "Montenegro", "الجبل الأسود", "382"),
    ("MS", "Montserrat", "مونتسرات", "1664"),
    ("MA", "Morocco", "المغرب", "212"),
    ("MZ", "Mozambique", "موزمبيق", "258"),
    ("MM", "Myanmar", "ميانمار", "95"),
    ("NA", "Namibia", "ناميبيا", "264"),
    ("NR", "Nauru", "ناورو", "674"),
    ("NP", "Nepal", "نيبال", "977"),
    ("NL", "Netherlands", "هولندا", "31"),
    ("AN", "Netherlands Antilles", "جزر الأنتيل الهولندية", "599"),
    ("NC", "New Caledonia", "كاليدونيا الجديدة", "687"),
    ("NZ", "New Zealand", "نيوزيلندا", "64"),
    ("NI", "Nicaragua", "نيكاراغوا", "505"),
    ("NE", "Niger", "النيجر", "227"),
    ("NG", "Nigeria", "نيجيريا", "234"),
    ("NU", "Niue", "نييوي", "683"),
    ("KP", "North Korea", "كوريا الشمالية", "850"),
    ("MP", "Northern Mariana Islands", "جزر ماريانا الشمالية", "1670"),
    ("NO", "Norway", "النرويج", "47"),
    ("OM", "Oman", "عمان", "968"),
    ("PK", "Pakistan", "باكستان", "92"),
    ("PW", "Palau", "بالاو", "680"),
    ("PS", "Palestine", "فلسطين", "970"),
    ("PA", "Panama", "بنما", "507"),
    ("PG", "Papua New Guinea", "بابوا غينيا الجديدة", "675"),
    ("PY", "Paraguay", "باراغواي", "595"),
    ("PE", "Peru", "بيرو", "51"),
    ("PH", "Philippines", "الفلبين", "63"),
    ("PN", "Pitcairn", "بيتكيرن", "64"),
    ("PL", "Poland", "بولندا", "48"),
    ("PT", "Portugal", "البرتغال", "351"),
    ("PR", "Puerto Rico", "بورتوريكو", "1787"),
    ("QA", "Qatar", "قطر", "974"),
    ("CG", "Republic of the Congo", "جمهورية الكونغو", "242"),
    ("RE", "Reunion", "ريونيون", "262"),
    ("RO", "Romania", "رومانيا", "40"),
    ("RU", "Russia", "روسيا", "7"),
    ("RW", "Rwanda", "رواندا", "250"),
    ("BL", "Saint Barthelemy", "سان بارتيلمي", "590"),
    ("SH", "Saint Helena", "سانت هيلينا", "290"),
    ("KN", "Saint Kitts and Nevis", "سانت كيتس ونيفيس", "1869"),
    ("LC", "Saint Lucia", "سانت لوسيا", "1758"),
    ("MF", "Saint Martin", "سانت مارتن", "590"),
    ("PM", "Saint Pierre and Miquelon", "سان بيير وميكلون", "508"),
    ("VC", "Saint Vincent and the Grenadines", "سانت فينسنت والغرينادين", "1784"),
    ("WS", "Samoa", "ساموا", "685"),
    ("SM", "San Marino", "سان مارينو", "378"),
    ("ST", "Sao Tome and Principe", "ساو تومي وبرينسيبي", "239"),
    ("SA", "Saudi Arabia", "المملكة العربية السعودية", "966"),
    ("SN", "Senegal", "السنغال", "221"),
    ("RS", "Serbia", "صربيا", "381"),
    ("SC", "Seychelles", "سيشل", "248"),
    ("SL", "Sierra Leone", "سيراليون", "232"),
    ("SG", "Singapore", "سنغافورة", "65"),
    ("SX", "Sint Maarten", "سينت مارتن", "1721"),
    ("SK", "Slovakia", "سلوفاكيا", "421"),
    ("SI", "Slovenia", "سلوفينيا", "386"),
    ("SB", "Solomon Islands", "جزر سليمان", "677"),
    ("SO", "Somalia", "الصومال", "252"),
    ("ZA", "South Africa", "جنوب أفريقيا", "27"),
    ("KR", "South Korea", "كوريا الجنوبية", "82"),
    ("SS", "South Sudan", "جنوب السودان", "211"),
    ("ES", "Spain", "إسبانيا", "34"),
    ("LK", "Sri Lanka", "سريلانكا", "94"),
    ("SD", "Sudan", "السودان", "249"),
    ("SR", "Suriname", "سورينام", "597"),
    ("SJ", "Svalbard and Jan Mayen", "سفالبارد ويان ماين", "47"),
    ("SZ", "Swaziland", "سوازيلاند", "268"),
    ("SE", "Sweden", "السويد", "46"),
    ("CH", "Switzerland", "سويسرا", "41"),
    ("SY", "Syria", "سوريا", "963"),
    ("TW", "Taiwan", "تايوان", "886"),
    ("TJ", "Tajikistan", "طاجيكستان", "992"),
    ("TZ", "Tanzania", "تنزانيا", "255"),
    ("TH", "Thailand", "تايلاند", "66"),
    ("TG", "Togo", "توغو", "228"),
    ("TK", "Tokelau", "توكيلاو", "690"),
    ("TO", "Tonga", "تونغا", "676"),
    ("TT", "Trinidad and Tobago", "ترينيداد وتوباغو", "1868"),
    ("TN", "Tunisia", "تونس", "216"),
    ("TR", "Turkey", "تركيا", "90"),
    ("TM", "Turkmenistan", "تركمانستان", "993"),
    ("TC", "Turks and Caicos Islands", "جزر توركس وكايكوس", "1649"),
    ("TV", "Tuvalu", "توفالو", "688"),
    ("VI", "U.S. Virgin Islands", "جزر العذراء الأمريكية", "1340"),
    ("UG", "Uganda", "أوغندا", "256"),
    ("UA", "Ukraine", "أوكرانيا", "380"),
    ("GB", "United Kingdom", "المملكة المتحدة", "44"),
    ("US", "United States", "الولايات المتحدة", "1"),
    ("UY", "Uruguay", "أوروغواي", "598"),
    ("UZ", "Uzbekistan", "أوزبكستان", "998"),
    ("VU", "Vanuatu", "فانواتو", "678"),
    ("VA", "Vatican", "الفاتيكان", "379"),
    ("VE", "Venezuela", "فنزويلا", "58"),
    ("VN", "Vietnam", "فيتنام", "84"),
    ("WF", "Wallis and Futuna", "والس وفوتونا", "681"),
    ("EH", "Western Sahara", "الصحراء الغربية", "212"),
    ("YE", "Yemen", "اليمن", "967"),
    ("ZM", "Zambia", "زامبيا", "260"),
    ("ZW", "Zimbabwe", "زيمبابوي", "263"),
    # Pad to cover any leftover ids referenced by users.country_id (max=246).
    ("AX", "Aland Islands", "جزر أولاند", "358"),
    ("BQ", "Bonaire", "بونير", "599"),
    ("GF", "French Guiana", "غويانا الفرنسية", "594"),
    ("TF", "French Southern Territories", "أراض فرنسية جنوبية وأنتارتيكية", "262"),
    ("GP", "Guadeloupe", "غوادلوب", "590"),
    ("HM", "Heard Island and McDonald Islands", "جزيرة هيرد وجزر ماكدونالد", "672"),
    ("MQ", "Martinique", "مارتينيك", "596"),
    ("UM", "United States Minor Outlying Islands", "جزر الولايات المتحدة الصغيرة النائية", "1"),
    ("BV", "Bouvet Island", "جزيرة بوفيه", "47"),
    ("GS", "South Georgia and the South Sandwich Islands", "جورجيا الجنوبية وجزر ساندويتش الجنوبية", "500"),
]

def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "''")

print("-- Auto-generated countries seed (id=1 -> United Arab Emirates)")
print("SET FOREIGN_KEY_CHECKS=0;")
print("TRUNCATE TABLE countries;")
values = []
for i, (code, en, ae, phone) in enumerate(COUNTRIES, start=1):
    values.append(
        f"({i}, '{esc(code)}', '{esc(en)}', '{esc(ae)}', '{esc(phone)}', 1, 1)"
    )
print(
    "INSERT INTO countries (id, code, name_en, name_ae, phone_code, status, created_by) VALUES"
)
print(",\n".join(values) + ";")
print("SET FOREIGN_KEY_CHECKS=1;")
print(f"-- Seeded {len(COUNTRIES)} rows")
